version: 0.2

environment_variables:
  plaintext:
    PYTHON_VERSION: 3.8

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - make setup
      - make install
  build:
    commands:
      - make lint
      - make test
  post_build:
    commands:
      - echo Linting & Testing completed on `date`