version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Install
      - make install
  build:
    commands:
      - python application.py
  post_build:
    commands:
      - echo Build completed on `date`