version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo install
      - make install
  build:
    commands:
      - echo build
      - make lint
      - make test
  post_build:
    commands:
      - echo Build completed on `date`